CLEAR 

CADENA= "BRITHANY DEL CISNE SOLANO ALAVA"

*PRIMER NOMBRE
?SUBSTR(CADENA,1,AT(" ",CADENA,1)-1)

*SEGUNDO NOMBRE
?SUBSTR(CADENA,AT(" ",CADENA,1)+1,AT(" ",CADENA,3)-AT(" ",CADENA,1))

*PRIMER APELLIDO
?SUBSTR(CADENA,AT(" ",CADENA,3)+1,AT(" ",CADENA,4)-AT(" ",CADENA,3))

*SEGUNDO APELLIDO
?SUBSTR(CADENA,AT(" ",CADENA,4)+1,AT(" ",CADENA,4))
@1,100 SAY "-BRITHANY SOLANO"
WAIT "PRESIONE" WINDOW  AT 1,1
 
 
 
 