CLEAR
@1,100 SAY "-BRITHANY SOLANO"
E=0
@14,20 SAY "EDAD" GET E
READ
IF E>18 THEN
@16,20 SAY "PACIENTE MAYOR DE EDAD"
ELSE
IF E<17 THEN
@16,20 SAY "PACIENTE MENOR DE EDAD"

ENDIF
ENDIF
 WAIT "PRESIONE" WINDOW  AT 1,1

