CLEAR 
@1,100 SAY "-BRITHANY SOLANO"
DECLARE ELEMENTOS (6)
FOR N=1 TO 6
ELEMENTOS(N)=SPACE(40)
@10,20 GET ELEMENTOS(N)
READ 
ENDFOR

*MOSTRAR LA MATRIZ ANTES DE ORDENAR
?"MATRIZ ORIGINAL"
FOR N=1 TO 6
?ELEMENTOS(N)
ENDFOR

ASORT(ELEMENTOS)

*INVESTIR MATRIZ
LCELEMENTOS=0
FOR N=1 TO (1/2)
LCELEMENTOS=ELEMENTOS(N)
ELEMENTOS(N)=ELEMENTOS(7-N)
ELEMENTOS(7-N)=LCELEMENTOS
ENDFOR

*MOSTRAR LA MATRIZ ORDENADA

?"MATRIZ ORDENADA"
FOR N=1 TO 6
?ELEMENTOS(N)
ENDFOR
 WAIT "PRESIONE" WINDOW  AT 1,1
 