CLEAR
@1,100 SAY "-BRITHANY SOLANO"

DECLARE PRODUCTOS (10)

FOR N=1 TO 10
PRODUCTOS(N)= SPACE(50)
@10,20 GET PRODUCTOS(N)
READ 
ENDFOR
FOR N=1 TO 10
? PRODUCTOS(N)
ENDFOR
 WAIT "PRESIONE" WINDOW  AT 1,1