CLEAR
@1,100 SAY "-BRITHANY SOLANO"

DECLARE LISTA(1)
NOMBRE=SPACE(50)
ELEMENTO=0
CLEAR
DO WHILE NOMBRE#"FIN"
NOMBRE=SPACE(50)
@14,20 SAY "INGRESE NOMBRE" GET NOMBRE
READ
IF NOMBRE#"FIN"
ELEMENTO=ELEMENTO+1

DECLARE LISTA(ELEMENTO)
LISTA(ELEMENTO)=NOMBRE
ENDIF
ENDDO

FOR I=1 TO ALEN(LISTA)
?LISTA(I)
ENDFOR

@1,100 SAY "-BRITHANY SOLANO"
 WAIT "PRESIONE" WINDOW  AT 1,1