*PROMEDIO DE 3 VALORES QUE INGRESEN POR TECLADO

CLEAR
@1,100 SAY "-BRITHANY SOLANO"
 
A=0
B=0
C=0

@10,20 SAY "INGRESE VALOR DE A" GET A
@11,20 SAY "INGRESE VALOR DE B" GET B
@12,20 SAY "INGRESE VALOR DE C" GET C
READ
P=(A+B+C)/3

@14,20 SAY "EL PROMEDIO ES" + TRANSFORM(P,"99999.9")
 WAIT "PRESIONE" WINDOW  AT 1,1