SET DEFAULT TO JUSTPATH(SYS(16,1))
OPCION=99
DO WHILE opcion#0


CLEAR
@1,100 SAY "BRITHANY DEL CISNE SOLANO ALAVA"

*----------------------MENÚ-------------*

@5,10 SAY "1.PROMEDIO DE 3 VALORES"
@6,10 SAY "2.EDAD DE PACIENTE INGRESADA POR TECLADO"
@7,10 SAY "3.10 PRIMEROS NUMEROS PARES"
@8,10 SAY  "4.PRIMEROS 5 NUMEROS IMPARES"
@9,10 SAY "5.PRIMEROS 7 MULTIPLOS DE 11"
@10,10 SAY  "6.#FACTORIAL DE N"
@11,10 SAY  "7.CALCULADORA"
@12,10 SAY  "8.VALOR DE DESCUENTO"
@13,10 SAY  "9.VALOR PROMEDIO DE LOS 10 PRIMEROS NUMEROS NATURALES"
@14,10 SAY  "10. CALCULADORA CON DO WHILE"
@15,10 SAY  "11.MATRIZ DE 10 PRODUCTOS Q INGRESAN POR TECLADO"
@16,10 SAY  "12. MATRIZ CON LOS N=NUMEROS PRIMOS DE 3"
@17,10 SAY  "13. MATRIZ HASTA Q SE ESCRIBA LA PALABRA 'FIN'"
@18,10 SAY  "14.MATRIZ ASCENDENTE DE APELLIDOS"
@19,10 SAY  "15. MATRIZ DESCENDENTE DE APELLIDOS"
@20,10 SAY  "16.MATRIZ DE 10 ELEMENTOS DE FORMA ASCENDENTE"
@21,10 SAY  "17. MATRIZ 6 ELEMENTOS DE FORMA DESCENDENTE"
@22,10 SAY  "18. CADENA D4E NUESTRO NOMBRE"
@23,10 SAY  "19. CADENA NOMBRE DEL COLEGIO"
@24,10 SAY  "20.SELECCIÓN DE GÉNERO"
@25,10 SAY "PRESIONE 0 PARA SALIR"



@26,10 SAY  "INGRESE OPCION DEL MENU" GET OPCION
READ
IF OPCION= 1
DO "PROMEDIO DE 3 VALORES.PRG"
ENDIF

IF OPCION= 2
DO "INGRESAR EDAD.PRG"
ENDIF

IF OPCION= 3
DO "10 PRIMEROS NUMEROS PARES.PRG"
ENDIF

IF OPCION= 4
DO "5 NUMEROS IMPARES.PRG"
ENDIF

IF OPCION= 5
DO "MULTIPLOS.PRG"
ENDIF

IF OPCION= 6
DO "numero facotiral.prg"
ENDIF

IF OPCION= 7
DO "CALCULADORA.PRG"
ENDIF

IF OPCION= 8
DO "valor de descuent0.prg"
ENDIF

IF OPCION= 9
DO "valor rome3diode 10 numeros.PRG"
ENDIF

IF OPCION= 10
DO "CALCULADORA CON DOWHILE.PRG"
ENDIF

IF OPCION= 11
DO "matriz de 10 proictos.prg"
ENDIF

IF OPCION= 12
DO "N NUMEROS DE 3.PRG"
ENDIF

IF OPCION= 13
DO "MATRIZ FIIN.PRG"
ENDIF

IF OPCION= 14
DO "MATIZ ASCENDENTE.PRG"
ENDIF

IF OPCION= 15
DO "MATIZ DESCENDENTE.PRG"
ENDIF

IF OPCION= 16
DO "MATIZ 10 ELEMENTOS.PRG"
ENDIF

IF OPCION= 17
DO "MATIZ 6 ELEMENTOS.PRG"
ENDIF

IF OPCION= 18
DO "cadena.prg"
ENDIF

IF OPCION= 19
DO "UEMGDC.PRG"
ENDIF

IF OPCION= 20
DO "SELECCION E GENERO.PRG"
ENDIF

ENDDO
MESSAGEBOX("GRACIAS POR USAR ESTA APLICACIÓN",0+64,"AVISO")


